# Generated by Django 5.1.3 on 2024-12-18 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumnalia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovia',
            old_name='nombre',
            new_name='nom_via',
        ),
        migrations.RemoveField(
            model_name='dat_per',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='dat_per',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='dat_per',
            name='tipo_via',
        ),
        migrations.AddField(
            model_name='dat_per',
            name='fk_nom_mun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alumnalia.municipios', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='dat_per',
            name='fk_nom_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alumnalia.provincias', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='dat_per',
            name='fk_nom_via',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alumnalia.tipovia', verbose_name='Tipo de via'),
        ),
    ]
