# Generated by Django 5.1.3 on 2024-12-19 21:56

import app_alumnalia.modelos.modelFormacion
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_alumnalia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudio_Profesion",
            fields=[
                (
                    "pk_est_pro",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Estudio Profecional",
                    ),
                ),
                (
                    "desc_est_pro",
                    models.CharField(
                        max_length=220,
                        verbose_name="Descripcion de la Estudio Profesional",
                    ),
                ),
            ],
            options={
                "db_table": "Estudio_Profesional",
            },
        ),
        migrations.CreateModel(
            name="Familia_Profesion",
            fields=[
                (
                    "pk_fm_pro",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Entidad Formadora",
                    ),
                ),
                (
                    "desc_fm_pro",
                    models.CharField(
                        max_length=200,
                        verbose_name="Descripcion de la Familia Profesional",
                    ),
                ),
            ],
            options={
                "db_table": "Familia_Profesional",
            },
        ),
        migrations.CreateModel(
            name="Ent_For",
            fields=[
                (
                    "pk_ent_for",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Entidad Formadora",
                    ),
                ),
                (
                    "nom_ent_for",
                    models.CharField(
                        max_length=44, verbose_name="nombre de Entidad Formadora"
                    ),
                ),
                (
                    "Area_for_ent_for",
                    models.CharField(
                        max_length=44,
                        verbose_name="area de formacion de Entidad Formadora",
                    ),
                ),
                (
                    "email_ent_for",
                    models.EmailField(
                        max_length=254, verbose_name="correo de la entidad"
                    ),
                ),
                (
                    "nif_ent_for",
                    models.CharField(
                        max_length=20, verbose_name="NIF de Entidad Formadora"
                    ),
                ),
                ("fec_fin_ent_for", models.DateField(verbose_name="Fecha de fin")),
                ("fec_ini_ent_for", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "area_prof_ent_for",
                    models.CharField(
                        max_length=44,
                        verbose_name="Area Porfecional de Entidad Formadora",
                    ),
                ),
                (
                    "cm_ent_for",
                    models.CharField(
                        max_length=5,
                        verbose_name="Codigo del municipio de Entidad Formadora",
                    ),
                ),
                (
                    "web_ent_for",
                    models.CharField(
                        max_length=100,
                        verbose_name="link de la web de Entidad Formadora",
                    ),
                ),
                (
                    "horas_ent_for",
                    models.IntegerField(verbose_name="horas de la Entidad Formadora"),
                ),
                (
                    "idt_ent_for",
                    models.IntegerField(
                        verbose_name="identificador de la Entiad Formadora"
                    ),
                ),
                (
                    "den_ent_for",
                    models.CharField(
                        max_length=100, verbose_name="Denominacion de Entidad Formadora"
                    ),
                ),
                (
                    "amb_ent_for",
                    models.CharField(
                        max_length=100, verbose_name="Ambito de Entidad Formadora"
                    ),
                ),
                (
                    "mod_ent_for",
                    models.CharField(
                        max_length=50, verbose_name="Modalidad de Entidad Formadora"
                    ),
                ),
                (
                    "num_grupo",
                    models.IntegerField(
                        verbose_name="Numero de grupo de la Entidad Formadora"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=15,
                        validators=[
                            app_alumnalia.modelos.modelFormacion.validar_longitud_nueve
                        ],
                        verbose_name="telefono de Entidad Formadora",
                    ),
                ),
                (
                    "fk_com_ent_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Comarca",
                        to="app_alumnalia.comarca",
                    ),
                ),
                (
                    "fk_mun_ent_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Municipios",
                        to="app_alumnalia.municipios",
                    ),
                ),
                (
                    "fk_fam_pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Familia_Profesion",
                        to="app_alumnalia.familia_profesion",
                    ),
                ),
            ],
            options={
                "db_table": "Ent_For",
            },
        ),
    ]
