# Generated by Django 5.1.3 on 2024-12-20 05:46

import app_alumnalia.modelos.modelFormacion
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_alumnalia", "0002_estudio_profesion_familia_profesion_ent_for"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambito",
            fields=[
                (
                    "pk_amb",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Ambito",
                    ),
                ),
                (
                    "desc_amb",
                    models.CharField(
                        max_length=200, verbose_name="Descripcion del Ambito"
                    ),
                ),
            ],
            options={
                "db_table": "Ambito",
            },
        ),
        migrations.CreateModel(
            name="Calendario",
            fields=[
                (
                    "pk_cal",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Calendario",
                    ),
                ),
                (
                    "dat_ini_cal",
                    models.DateField(verbose_name="Fecha de inicio del curso"),
                ),
                (
                    "dat_fin_cal",
                    models.DateField(verbose_name="Fecha de fin del curso"),
                ),
                (
                    "nom_grup_cal",
                    models.CharField(
                        max_length=30,
                        verbose_name="Numero de grupo asignado en el calendario",
                    ),
                ),
            ],
            options={
                "db_table": "Calendario",
            },
        ),
        migrations.CreateModel(
            name="Denominacion",
            fields=[
                (
                    "pk_deno",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Denominacion",
                    ),
                ),
                (
                    "desc_den",
                    models.CharField(
                        max_length=200, verbose_name="Descripcion de la Denominacion"
                    ),
                ),
            ],
            options={
                "db_table": "Denominacion",
            },
        ),
        migrations.CreateModel(
            name="Escuela",
            fields=[
                (
                    "pk_esc",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Entidad Formadora",
                    ),
                ),
                (
                    "nom_esc",
                    models.CharField(
                        max_length=44, verbose_name="nombre de Entidad Formadora"
                    ),
                ),
                (
                    "email_esc",
                    models.EmailField(
                        max_length=254, verbose_name="correo de la entidad"
                    ),
                ),
                (
                    "nif_esc",
                    models.CharField(
                        max_length=20, verbose_name="NIF de Entidad Formadora"
                    ),
                ),
                (
                    "web_esc",
                    models.CharField(
                        max_length=100,
                        verbose_name="link de la web de Entidad Formadora",
                    ),
                ),
                (
                    "tel_esc",
                    models.CharField(
                        max_length=15,
                        validators=[
                            app_alumnalia.modelos.modelFormacion.validar_longitud_nueve
                        ],
                        verbose_name="telefono de Entidad Formadora",
                    ),
                ),
            ],
            options={
                "db_table": "Escuela",
            },
        ),
        migrations.AlterField(
            model_name="comarca_provincias",
            name="fk_com",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Comarca_provincias",
                to="app_alumnalia.comarca",
                verbose_name="id de la Comarca",
            ),
        ),
        migrations.AlterField(
            model_name="comarca_provincias",
            name="fk_pro",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Comarca_provincias",
                to="app_alumnalia.provincias",
                verbose_name="id de la Provicia",
            ),
        ),
        migrations.CreateModel(
            name="Cusrso",
            fields=[
                (
                    "pk_cal",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Curso",
                    ),
                ),
                (
                    "idt_ent_for",
                    models.IntegerField(
                        verbose_name="identificador de la Entiad Formadora"
                    ),
                ),
                (
                    "area_prof_ent_for",
                    models.CharField(
                        max_length=44,
                        verbose_name="Area Porfecional de Entidad Formadora",
                    ),
                ),
                (
                    "horas_ent_for",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="horas de la Entidad Formadora",
                    ),
                ),
                (
                    "mod_cur",
                    models.CharField(
                        choices=[
                            ("", "Seleccione una opción"),
                            ("1", "Presencial"),
                            ("2", "En línea"),
                            ("3", "Mixta"),
                        ],
                        default="",
                        max_length=1,
                        verbose_name="Modalidad de estudio",
                    ),
                ),
                (
                    "fk_amb_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ambito",
                        to="app_alumnalia.ambito",
                        verbose_name="Ambito de Entidad Formadora",
                    ),
                ),
                (
                    "fk_fam_pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Cusrso",
                        to="app_alumnalia.familia_profesion",
                    ),
                ),
                (
                    "fk_den_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Denomincion",
                        to="app_alumnalia.denominacion",
                    ),
                ),
            ],
            options={
                "db_table": "Curso",
            },
        ),
        migrations.CreateModel(
            name="Oferta_Formativa",
            fields=[
                (
                    "pk_Ofe_for",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Oferta Formadora",
                    ),
                ),
                (
                    "nom_ofe",
                    models.CharField(max_length=44, verbose_name="nombre de la oferta"),
                ),
                (
                    "Area_for_ent_for",
                    models.CharField(
                        max_length=44, verbose_name="Area de formacion de la oferta"
                    ),
                ),
                (
                    "fk_cal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Escuela",
                        to="app_alumnalia.calendario",
                    ),
                ),
                (
                    "fk_com",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Escuela",
                        to="app_alumnalia.comarca",
                    ),
                ),
                (
                    "fk_cur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Escuela",
                        to="app_alumnalia.cusrso",
                    ),
                ),
                (
                    "fk_esc_pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Escuela",
                        to="app_alumnalia.escuela",
                    ),
                ),
                (
                    "fk_mun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Escuela",
                        to="app_alumnalia.municipios",
                    ),
                ),
                (
                    "fk_pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Escuela",
                        to="app_alumnalia.provincias",
                    ),
                ),
            ],
            options={
                "db_table": "Oferta_Formativa",
            },
        ),
    ]
