# Generated by Django 5.1.3 on 2024-12-13 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_alumnalia", "0007_comarca_comarca_provincias_provincias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inf_prof",
            name="cv_adj_inf_pro",
            field=models.FileField(
                upload_to="pdfs/", verbose_name="Adjunta tu currículum en formato PDF."
            ),
        ),
        migrations.CreateModel(
            name="Municipios",
            fields=[
                (
                    "pk_mun",
                    models.SmallAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id de Provincias",
                    ),
                ),
                (
                    "nom_mun",
                    models.CharField(
                        max_length=30, verbose_name="nombre de la Municipios"
                    ),
                ),
                (
                    "fk_com",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Municipios",
                        to="app_alumnalia.comarca",
                    ),
                ),
            ],
            options={
                "db_table": "Municipios",
            },
        ),
    ]
