# Generated by Django 5.1.3 on 2024-12-16 15:41

import app_alumnalia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumnalia', '0009_familia_profesion_rename_pk_com_comarca_pk_com_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comarca_provincias',
            name='nom_cam_pro',
        ),
        migrations.RemoveField(
            model_name='ent_for',
            name='cm_ent_for',
        ),
        migrations.RemoveField(
            model_name='ent_for',
            name='telefono',
        ),
        migrations.AddField(
            model_name='comarca_provincias',
            name='fk_com',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Comarca_provincias', to='app_alumnalia.comarca'),
        ),
        migrations.AddField(
            model_name='comarca_provincias',
            name='fk_pro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Comarca_provincias', to='app_alumnalia.provincias'),
        ),
        migrations.AddField(
            model_name='dat_per',
            name='fn_per_enc',
            field=models.CharField(default='', max_length=15, verbose_name='Fecha de nacimiento encriptada'),
        ),
        migrations.AddField(
            model_name='dat_per',
            name='tel_per_enc',
            field=models.CharField(default='', max_length=10, verbose_name='Teléfono encriptada'),
        ),
        migrations.AddField(
            model_name='ent_for',
            name='cp_ent_for',
            field=models.CharField(default='', max_length=5, verbose_name='Codigo postal'),
        ),
        migrations.AddField(
            model_name='ent_for',
            name='tel_ent_for',
            field=models.IntegerField(default=0, validators=[app_alumnalia.models.validar_longitud_nueve], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='comarca',
            name='nom_com',
            field=models.CharField(max_length=30, verbose_name='Nombre de la Comarca'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='cn_per',
            field=models.CharField(max_length=150, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='dir_per',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='dni_per',
            field=models.CharField(max_length=15, unique=True, validators=[app_alumnalia.models.validar_dni], verbose_name='DNI/NIE'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='email_per',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='fn_per',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='nom_per',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='noti_per',
            field=models.BooleanField(default=False, verbose_name='Notificaciones de oportunidades formativas'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='sex_per',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Mujer'), ('2', 'Hombre'), ('3', 'Prefiero no responder'), ('4', 'Otro')], default='', max_length=1, verbose_name='Género de la persona'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='tel_per',
            field=models.IntegerField(validators=[app_alumnalia.models.validar_longitud_nueve], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='term_per',
            field=models.BooleanField(default=False, verbose_name='Términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='dat_per',
            name='uso_datos_per',
            field=models.BooleanField(default=False, verbose_name='Fines de gestión académica y administrativa'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='Area_for_ent_for',
            field=models.CharField(max_length=44, verbose_name='Area de formacion'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='amb_ent_for',
            field=models.CharField(max_length=100, verbose_name='Ambito'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='area_prof_ent_for',
            field=models.CharField(max_length=44, verbose_name='Area Porfesional'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='den_ent_for',
            field=models.CharField(max_length=100, verbose_name='Denominacion'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='email_ent_for',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='horas_ent_for',
            field=models.IntegerField(verbose_name='Horas'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='idt_ent_for',
            field=models.IntegerField(verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='mod_ent_for',
            field=models.CharField(max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='nif_ent_for',
            field=models.CharField(max_length=20, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='nom_ent_for',
            field=models.CharField(max_length=44, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='num_grupo',
            field=models.IntegerField(verbose_name='Numero de grupo'),
        ),
        migrations.AlterField(
            model_name='ent_for',
            name='web_ent_for',
            field=models.URLField(max_length=100, verbose_name='URL de la web'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='cert_esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='Especifique su certificación'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='cert_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Sí'), ('2', 'No')], default='', max_length=1, verbose_name='¿Tienes alguna certificación docente?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='comp_dig_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Sí'), ('2', 'No')], default='', max_length=1, verbose_name='¿Posees competencias digitales específicas (ej. DigCompEdu)?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='exp_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Menos de 1 año'), ('2', 'De 1 a 3 años'), ('3', 'De 4 a 6 años'), ('4', 'Más de 6 años')], default='', max_length=1, verbose_name='¿Cuántos años de experiencia tienes como formador/a?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='fk_per_inf_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alumnalia.dat_per', verbose_name='fk de Datos de personas'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='for_imp_esp_inf_pro',
            field=models.CharField(max_length=255, verbose_name='Especifique que formación ha impartido'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='for_imp_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Formación profesional'), ('2', 'Formación universitaria'), ('3', 'Formación empresarial'), ('4', 'Cursos en línea'), ('5', 'Otros')], default='', max_length=1, verbose_name='Qué tipo de formación has impartido'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='franja_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Mañana (8:00-14:00)'), ('2', 'Tarde (14:00-20:00)'), ('3', 'Noche (20:00-23:00)')], default='', max_length=1, verbose_name='En qué franjas horarias estás disponible para impartir clases?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='herr_esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='Especifique otra herramienta tecnológica'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='herr_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Moodle'), ('2', 'Microsoft Teams'), ('3', 'Zoom'), ('4', 'Google Classroom'), ('5', 'Otros')], default='', max_length=1, verbose_name='¿Qué herramientas tecnológicas utilizas en tus clases?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='mod_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Presencial'), ('2', 'En línea'), ('3', 'Mixta')], default='', max_length=1, verbose_name='Qué modalidades de enseñanza prefieres impartir'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='tipo_alu_esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='Especifique el tipo de alumnos'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='tipo_alu_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Jóvenes'), ('2', 'Adultos'), ('3', 'Empresas'), ('4', 'Otros')], default='', max_length=1, verbose_name='Qué tipo de alumnado prefieres formar'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='tit_esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='Especifique título'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='tit_inf_pro',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('1', 'Técnico/a'), ('2', 'Grado universitario'), ('3', 'Máster'), ('4', 'Doctorado'), ('5', 'Otros')], default='', max_length=1, verbose_name='Título académico más alto obtenido'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='nom_mun',
            field=models.CharField(max_length=30, verbose_name='Nombre del Municipio'),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='nom_pro',
            field=models.CharField(max_length=30, verbose_name='Nombre de la Provincia'),
        ),
    ]
