# Generated by Django 5.1.3 on 2024-12-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumnalia', '0011_alter_estudio_profesion_desc_est_pro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('pk_tip_user', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id de tip de usurio')),
                ('nom_tip_user', models.CharField(max_length=10, verbose_name='Descripcion del tipo de usuario')),
                ('per_tip_user', models.SmallIntegerField(max_length=2, verbose_name='permiso del tipo de usuario')),
            ],
            options={
                'db_table': 'Tipo_Usuario',
            },
        ),
        migrations.RemoveField(
            model_name='ent_for',
            name='fk_com_ent_for',
        ),
        migrations.RemoveField(
            model_name='ent_for',
            name='fk_fam_pro',
        ),
        migrations.RemoveField(
            model_name='ent_for',
            name='fk_mun_ent_for',
        ),
        migrations.DeleteModel(
            name='Estudio_Profesion',
        ),
        migrations.RemoveField(
            model_name='comarca_provincias',
            name='nom_cam_pro',
        ),
        migrations.AddField(
            model_name='comarca_provincias',
            name='fk_com',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comarca_provincias', to='app_alumnalia.comarca'),
        ),
        migrations.AddField(
            model_name='comarca_provincias',
            name='fk_pro',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comarca_provincias', to='app_alumnalia.provincias'),
        ),
        migrations.DeleteModel(
            name='Familia_Profesion',
        ),
        migrations.DeleteModel(
            name='Ent_For',
        ),
    ]
