# Generated by Django 5.1.3 on 2024-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alumnalia', '0002_dat_per_fn_per_alter_inf_prof_tit_inf_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inf_prof',
            name='cert_esp_inf_pro',
            field=models.CharField(max_length=30, verbose_name='Especifique su cert_inf_pro'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='cert_inf_pro',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No'), ('3', 'Especificar')], default='Seleccione una opción', verbose_name='¿Tienes alguna certificación docente?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='comp_dig_esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='Especifique cuales'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='comp_dig_inf_pro',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No'), ('3', 'Especificar')], default='Seleccione una opción', verbose_name='¿Posees competencias digitales específicas (ej. DigCompEdu)?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='¿En qué área está tu especialización principal?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='exp_inf_pro',
            field=models.IntegerField(choices=[('1', 'Menos de 1 año'), ('2', 'De 1 a 3 años'), ('3', 'De 4 a 6 años'), ('4', 'Más de 6 años')], default='Seleccione una opción', verbose_name='¿Cuántos años de experiencia tienes como formador/a?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='for_imp_inf_pro',
            field=models.IntegerField(choices=[('1', 'Formación profesional'), ('2', 'Formación universitaria'), ('3', 'Formación empresarial'), ('4', 'Cursos en línea'), ('5', 'Otros')], default='Seleccione una opción', verbose_name='Qué tipo de formación has impartido'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='franja_inf_pro',
            field=models.IntegerField(choices=[('1', 'Mañana (8:00-14:00)'), ('2', 'Tarde (14:00-20:00)'), ('3', 'Noche (20:00-23:00)')], default='Seleccione una opción', verbose_name='En qué franjas horarias estás disponible para impartir clases?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='herr_esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='Especifique otra herr_inf_pro'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='herr_inf_pro',
            field=models.IntegerField(choices=[('1', 'Moodle'), ('2', 'Microsoft Teams'), ('3', 'Zoom'), ('4', 'Google Classroom'), ('5', 'Otros')], default='Seleccione una opción', verbose_name='¿Qué herramientas tecnológicas utilizas en tus clases?'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='mod_inf_pro',
            field=models.IntegerField(choices=[('1', 'Presencial'), ('2', 'En línea'), ('3', 'Mixta')], default='Seleccione una opción', verbose_name='Qué modalidades de enseñanza prefieres impartir'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='tipo_alu_esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='Especifique tipo_alu_inf_pro'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='tipo_alu_inf_pro',
            field=models.IntegerField(choices=[('1', 'Jóvenes'), ('2', 'Adultos'), ('3', 'Empresas'), ('4', 'Otros')], default='Seleccione una opción', verbose_name='Qué tipo de alumnado prefieres formar'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='tit_esp_inf_pro',
            field=models.CharField(max_length=15, verbose_name='Otro tit_inf_pro'),
        ),
        migrations.AlterField(
            model_name='inf_prof',
            name='tit_inf_pro',
            field=models.IntegerField(choices=[('1', 'Técnico/a'), ('2', 'Grado universitario'), ('3', 'Máster'), ('4', 'Doctorado'), ('5', 'Otros')], default='Seleccione una opción', verbose_name='Título académico más alto obtenido'),
        ),
    ]
